version: '3'

services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: abc
  web:
    build:
      context: webapp/
      dockerfile: web.dockerfile
    command: /home/proj/scripts/init.sh
    volumes:
      - "./webapp/:/home/proj/"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: mydb
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: abc
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    depends_on:
      - mydb
