version: '3'

services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: abc
  web:
    build:
      context: webapp/
      dockerfile: web.dockerfile
    command: /home/proj/scripts/init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: mydb
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: abc
    ports:
      - "8000:8000"
    depends_on:
      - mydb
      - api
  api:
    build:
      context: apiserver/
      dockerfile: api.dockerfile
    command: flask run --host=0.0.0.0
    environment:
      - FOOBAR=aaa
    ports:
      - "5000:5000"

