version: '3'

services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: abc
  web:
    build: .
    command: ./init.sh
    environment:
      DBHOST: mydb
    ports:
      - "8000:8000"
    depends_on:
      - mydb
