version: '3'

services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: abc
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    command: ./init.sh
    environment:
      DBHOST: mydb
    ports:
      - "8000:8000"
    depends_on:
      - mydb
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    command: /home/run_nginx.sh
    environment:
      MY_IP: backend
      MY_PORT: 8000
    ports:
      - "80:80"
    depends_on:
      - backend
