name: Publish Docker image
on:
  push: {branches: master}
  # it will be triggered by release
  #  release is based on tag
  # release:
  #   types: [published]
jobs:
  push_arg_to_registry:
    name: Push Arg Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: docker/basic/arg/
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          repository: ywlee/my-arg-test
          tag_with_ref: true
          # Automatically tag the built Docker image with the Git reference of the workflow event
  push_api_server_to_registry:
    name: Push API server image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: dockercompose/microservices/apiserver/
          dockerfile: dockercompose/microservices/apiserver/api.dockerfile
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          repository: ywlee/k8s-test-api-server
          tags: ${{ github.run_id }}
  push_webapp_to_registry:
    name: Push webapp image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: dockercompose/microservices/webapp/
          dockerfile: dockercompose/microservices/webapp/web.dockerfile
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          repository: ywlee/k8s-test-webapp
          tags: ${{ github.run_id }}
  push_djpsql_to_registry:
    name: Push django2psql image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: dockercompose/django-psql/webapp/
          dockerfile: dockercompose/django-psql/webapp/web.dockerfile
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          repository: ywlee/djpsql
          tags: ${{ github.run_id }}
  push_runcmd_to_registry:
    name: Push runcmd image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: dockercompose/run-cmd/
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          repository: ywlee/runcmd
          tags: ${{ github.run_id }}
  push_hotreloading_to_registry:
    name: Push hot reloading image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: dockercompose/hot-reloading/webapp/
          dockerfile: dockercompose/hot-reloading/webapp/web.dockerfile
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          repository: ywlee/hotreloading
          tags: ${{ github.run_id }}
